### ISSUE TITLE
mac issus

### ISSUE THREAD

**Issue by smarttang** [reagent/http#3]
cc -static -Wall -g -I/usr/local/uriparser/include/uriparser -I./vendor/buffer/src   -c -o src/http.o src/http.c
In file included from src/http.c:4:
src/url.h:4:10: fatal error: 'Uri.h' file not found
# include <Uri.h>

```
     ^
```

1 error generated.
make: **\* [src/http.o] Error 1

**Comment by kongds** [comment]
You need install uriparser and modify makefile

**Comment by smarttang** [comment]
ok!thx~~
